# Generated by Django 4.0.4 on 2022-05-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('reservation_charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('geolocation', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=2)),
                ('long_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_start_time', models.TimeField()),
                ('destination_end_time', models.TimeField()),
                ('halt', models.IntegerField(help_text='Halt in second')),
                ('distance_between', models.FloatField(help_text='Distance between source & Destination', max_length=5)),
                ('ranking', models.SmallIntegerField(choices=[(1, '1'), (2, '2')])),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_route_destination', to='train.trainstation')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_route_source', to='train.trainstation')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('source_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_carry_passenger', models.SmallIntegerField()),
                ('reserved_vip_seat', models.SmallIntegerField()),
                ('is_superfast', models.BooleanField(default=False)),
                ('available_seater', models.ManyToManyField(to='train.trainseater')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_source', to='train.trainstation')),
                ('run_days', models.ManyToManyField(to='train.trainweek')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_destination', to='train.trainstation')),
            ],
        ),
    ]
